### PR TITLE
Deadline notification

### PR DESCRIPTION
**Pull request by yudukikun5120**
This is the first PR for this feature. This PR includes:
- **The assignment manager**. which fetches assignment information when users log in and keeps its consistency thanks to the PK constraint of IndexedDB.
- **Chrome notifications**. which are invoked when the assignment deadline is approaching. The UI is shown below.
<div align="center">
スクリーンショット 2022-11-10 18 49 37
</div>

- **Opt-in**. Users can turn off this feature themselves and this feature is turned off by default.

This PR does NOT include:
- Specification of the time before the deadline. The default value is 1 day.

@mkobayashime I would like to ask for your code review.

### CODE REVIEW

**Comment by mkobayashime** [comment]
@yudukikun5120 
Could you rebase to the latest main to get rid of off-topic commits?

**Comment by yudukikun5120** [comment]
@mkobayashime I rebased the code. Could I ask you for a code review?

**Comment by yudukikun5120** [comment]
@mkobayashime I found more work is needed and converted this PR to a draft. I appeal to you for waiting for a little bit.

**Comment by yudukikun5120** [comment]
@mkobayashime
I close this PR because this feature is too hard to debug if it's completed. But I have another plan and I'll work on it.

**Pull request closed without merging**
